{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "stats-agent-team.namespace" . }}
  labels:
    {{- include "stats-agent-team.labels" . | nindent 4 }}
{{- end }}
